package com.muziko.tageditor.myid3;

import com.muziko.tageditor.metadata.MusicMetadataConstants;

public interface MyID3v2Constants extends MusicMetadataConstants {
	int HEADER_FLAG_ID3v22_UNSYNCHRONISATION = 1 << 7;
	int HEADER_FLAG_ID3v22_COMPRESSION = 1 << 6;

	int HEADER_FLAG_ID3v23_UNSYNCHRONISATION = 1 << 7;
	int HEADER_FLAG_ID3v23_EXTENDED_HEADER = 1 << 6;
	int HEADER_FLAG_ID3v23_EXPERIMENTAL_INDICATOR = 1 << 5;

	int HEADER_FLAG_ID3v24_UNSYNCHRONISATION = 1 << 7;
	int HEADER_FLAG_ID3v24_EXTENDED_HEADER = 1 << 6;
	int HEADER_FLAG_ID3v24_EXPERIMENTAL_INDICATOR = 1 << 5;
	int HEADER_FLAG_ID3v24_FOOTER_PRESENT = 1 << 4;

	int FRAME_FLAG_ID3v24_TAG_ALTER_PRESERVATION = 1 << 14;
	int FRAME_FLAG_ID3v24_FILE_ALTER_PRESERVATION = 1 << 13;
	int FRAME_FLAG_ID3v24_READ_ONLY = 1 << 12;
	int FRAME_FLAG_ID3v24_GROUPING_IDENTITY = 1 << 6;
	int FRAME_FLAG_ID3v24_COMPRESSION = 1 << 3;
	int FRAME_FLAG_ID3v24_ENCRYPTION = 1 << 2;
	int FRAME_FLAG_ID3v24_UNSYNCHRONISATION = 1 << 1;
	int FRAME_FLAG_ID3v24_DATA_LENGTH_INDICATOR = 1 << 0;

	int FRAME_FLAG_ID3v23_TAG_ALTER_PRESERVATION = 1 << 15;
	int FRAME_FLAG_ID3v23_FILE_ALTER_PRESERVATION = 1 << 14;
	int FRAME_FLAG_ID3v23_READ_ONLY = 1 << 13;
	int FRAME_FLAG_ID3v23_COMPRESSION = 1 << 7;
	int FRAME_FLAG_ID3v23_ENCRYPTION = 1 << 6;
	int FRAME_FLAG_ID3v23_GROUPING_IDENTITY = 1 << 5;

	String CHAR_ENCODING_ISO = "ISO-8859-1";
	String CHAR_ENCODING_UTF_8 = "UTF-8";
	String CHAR_ENCODING_UTF_16 = "UTF-16";
	String CHAR_ENCODING_UTF_16_WITH_BOM = "UTF-16 with BOM";
	String CHAR_ENCODING_UTF_16_WITHOUT_BOM = "UTF-16 without BOM";

	int CHAR_ENCODING_CODE_ISO_8859_1 = 0;
	int CHAR_ENCODING_CODE_UTF_16_WITH_BOM = 1;
	int CHAR_ENCODING_CODE_UTF_16_NO_BOM = 2;
	int CHAR_ENCODING_CODE_UTF_8 = 3;

	int FRAME_HEADER_LENGTH = 10;
	int TAG_HEADER_LENGTH = 10;

	int PICTURE_TYPE_OTHER = 0x00;
	int PICTURE_TYPE_32X32_PIXELS_FILE_ICON_PNG_ONLY = 0x01;
	int PICTURE_TYPE_OTHER_FILE_ICON = 0x02;
	int PICTURE_TYPE_COVER_FRONT = 0x03;
	int PICTURE_TYPE_COVER_BACK = 0x04;
	int PICTURE_TYPE_LEAFLET_PAGE = 0x05;
	int PICTURE_TYPE_MEDIA_EG_LABEL_SIDE_OF_CD = 0x06;
	int PICTURE_TYPE_LEAD_ARTIST_LEAD_PERFORMER_SOLOIST = 0x07;
	int PICTURE_TYPE_ARTIST_PERFORMER = 0x08;
	int PICTURE_TYPE_CONDUCTOR = 0x09;
	int PICTURE_TYPE_BAND_ORCHESTRA = 0x0A;
	int PICTURE_TYPE_COMPOSER = 0x0B;
	int PICTURE_TYPE_LYRICIST_TEXT_WRITER = 0x0C;
	int PICTURE_TYPE_RECORDING_LOCATION = 0x0D;
	int PICTURE_TYPE_DURING_RECORDING = 0x0E;
	int PICTURE_TYPE_DURING_PERFORMANCE = 0x0F;
	int PICTURE_TYPE_MOVIE_VIDEO_SCREEN_CAPTURE = 0x10;
	int PICTURE_TYPE_A_BRIGHT_COLOURED_FISH = 0x11;
	int PICTURE_TYPE_ILLUSTRATION = 0x12;
	int PICTURE_TYPE_BAND_ARTIST_LOGOTYPE = 0x13;
	int PICTURE_TYPE_PUBLISHER_STUDIO_LOGOTYPE = 0x14;

}
